version: "3.9"
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - gradio_app

  gradio_app:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
